# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grados.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grados.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgrados.proto\"\x16\n\tOperacion\x12\t\n\x01\x61\x18\x01 \x01(\x01\"\x16\n\tResultado\x12\t\n\x01r\x18\x01 \x01(\x01\x32I\n\x0b\x43\x61lculadora\x12\x1c\n\x02\x43\x46\x12\n.Operacion\x1a\n.Resultado\x12\x1c\n\x02\x46\x43\x12\n.Operacion\x1a\n.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grados_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACION']._serialized_start=16
  _globals['_OPERACION']._serialized_end=38
  _globals['_RESULTADO']._serialized_start=40
  _globals['_RESULTADO']._serialized_end=62
  _globals['_CALCULADORA']._serialized_start=64
  _globals['_CALCULADORA']._serialized_end=137
# @@protoc_insertion_point(module_scope)
